
public enum ScreenName: String {
    case map = "Map TAB"
    case companySearch = "Company Search POP"
    case companyClusterList = "Company Cluster List POP"
    case companyPin = "Company Pin POP"
    case favourites = "Favourites TAB"
    case recommendations = "Recommendations SCR"
    case messagesContainer = "Thread List SCR"
    case company = "Company Details SCR"
    case coverLetter = "Cover Letter SCR"
    case editLetter = "Edit Letter SCR"
    case selectSkills = "Select Skills SCR"
    case selectPersonalAttributes = "Select PersonalAttributes Screen"
    case selectAvailabilityDates = "Select Availability Dates Screen"
    case selectDaysOfWeek = "Select Days of Week Screen"
    case selectJobRole = "Select Job Role Screen"
    case personalDetails = "Personal Details Screen"
    case addDocumentsScreen = "Add Documents Screen"
    case notSpecified = "Not specified"
}
