version: 2
jobs:
  test:
    macos:
      xcode: "11.2.1"
    steps:
      - checkout
      - run:
          name: Install CocoaPods
          command: pod install

      # Run tests.
      - run: bundle exec fastlane scan --scheme "All unit tests"
    
    macos:
      xcode: "11.2.1"
  deploy:
    macos:
      xcode: "11.2.1"
    steps:
      - checkout
      - deploy:
        name: Deploy
        command: fastlane release_appstore

workflows:
  version: 2
  test:
    jobs:
      - test
#      - deploy:
#        requires:
#          test
#        filters:
#        branches:
#          only: master
